#!/bin/bash

jupyter contrib nbextension install --user

# Allow collapsible headers
jupyter nbextension enable collapsible_headings/main

# Add a code formatter - requires yapf package
jupyter nbextension enable code_prettify/code_prettify

# Adds the "Solution" hiding option
jupyter nbextension enable exercise2/main

# Spellchecking
jupyter nbextension enable spellchecker/main


# Install nbstripout on git and clean the notebooks
nbstripout --install --attributes .gitattributes
nbstripout notes/*.ipynb

